// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat_types_samples.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chat_5ftypes_5fsamples_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chat_5ftypes_5fsamples_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chat_5ftypes_5fsamples_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chat_5ftypes_5fsamples_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chat_5ftypes_5fsamples_2eproto;
namespace chatmsg {
class ChatMessage;
struct ChatMessageDefaultTypeInternal;
extern ChatMessageDefaultTypeInternal _ChatMessage_default_instance_;
}  // namespace chatmsg
PROTOBUF_NAMESPACE_OPEN
template<> ::chatmsg::ChatMessage* Arena::CreateMaybeMessage<::chatmsg::ChatMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace chatmsg {

enum ChatMessageType : int {
  MSG_TYPE_TEXT = 0,
  MSG_TYPE_STICKER = 1,
  MSG_TYPE_NOTIFICATION = 2,
  MSG_TYPE_SYS = 3,
  ChatMessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ChatMessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ChatMessageType_IsValid(int value);
constexpr ChatMessageType ChatMessageType_MIN = MSG_TYPE_TEXT;
constexpr ChatMessageType ChatMessageType_MAX = MSG_TYPE_SYS;
constexpr int ChatMessageType_ARRAYSIZE = ChatMessageType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ChatMessageType_descriptor();
template<typename T>
inline const std::string& ChatMessageType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ChatMessageType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ChatMessageType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ChatMessageType_descriptor(), enum_t_value);
}
inline bool ChatMessageType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ChatMessageType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ChatMessageType>(
    ChatMessageType_descriptor(), name, value);
}
// ===================================================================

class ChatMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:chatmsg.ChatMessage) */ {
 public:
  inline ChatMessage() : ChatMessage(nullptr) {}
  ~ChatMessage() override;
  explicit PROTOBUF_CONSTEXPR ChatMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChatMessage(const ChatMessage& from);
  ChatMessage(ChatMessage&& from) noexcept
    : ChatMessage() {
    *this = ::std::move(from);
  }

  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChatMessage& operator=(ChatMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChatMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChatMessage* internal_default_instance() {
    return reinterpret_cast<const ChatMessage*>(
               &_ChatMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChatMessage& a, ChatMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ChatMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChatMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChatMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ChatMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ChatMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ChatMessage& from) {
    ChatMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChatMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "chatmsg.ChatMessage";
  }
  protected:
  explicit ChatMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kContentFieldNumber = 2,
    kSenderIdFieldNumber = 3,
    kSenderNameFieldNumber = 4,
    kReceiverIdFieldNumber = 5,
    kTimestampFieldNumber = 6,
    kMessageCmdFieldNumber = 8,
    kMessageTypeFieldNumber = 7,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string content = 2;
  void clear_content();
  const std::string& content() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_content(ArgT0&& arg0, ArgT... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // string sender_id = 3;
  void clear_sender_id();
  const std::string& sender_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_id();
  PROTOBUF_NODISCARD std::string* release_sender_id();
  void set_allocated_sender_id(std::string* sender_id);
  private:
  const std::string& _internal_sender_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_id(const std::string& value);
  std::string* _internal_mutable_sender_id();
  public:

  // string sender_name = 4;
  void clear_sender_name();
  const std::string& sender_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sender_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sender_name();
  PROTOBUF_NODISCARD std::string* release_sender_name();
  void set_allocated_sender_name(std::string* sender_name);
  private:
  const std::string& _internal_sender_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sender_name(const std::string& value);
  std::string* _internal_mutable_sender_name();
  public:

  // string receiver_id = 5;
  void clear_receiver_id();
  const std::string& receiver_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_receiver_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_receiver_id();
  PROTOBUF_NODISCARD std::string* release_receiver_id();
  void set_allocated_receiver_id(std::string* receiver_id);
  private:
  const std::string& _internal_receiver_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_receiver_id(const std::string& value);
  std::string* _internal_mutable_receiver_id();
  public:

  // string timestamp = 6;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // string message_cmd = 8;
  void clear_message_cmd();
  const std::string& message_cmd() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message_cmd(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message_cmd();
  PROTOBUF_NODISCARD std::string* release_message_cmd();
  void set_allocated_message_cmd(std::string* message_cmd);
  private:
  const std::string& _internal_message_cmd() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message_cmd(const std::string& value);
  std::string* _internal_mutable_message_cmd();
  public:

  // .chatmsg.ChatMessageType message_type = 7;
  void clear_message_type();
  ::chatmsg::ChatMessageType message_type() const;
  void set_message_type(::chatmsg::ChatMessageType value);
  private:
  ::chatmsg::ChatMessageType _internal_message_type() const;
  void _internal_set_message_type(::chatmsg::ChatMessageType value);
  public:

  // @@protoc_insertion_point(class_scope:chatmsg.ChatMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sender_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr receiver_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_cmd_;
    int message_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_chat_5ftypes_5fsamples_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChatMessage

// string id = 1;
inline void ChatMessage::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& ChatMessage::id() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.id)
}
inline std::string* ChatMessage::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.id)
  return _s;
}
inline const std::string& ChatMessage::_internal_id() const {
  return _impl_.id_.Get();
}
inline void ChatMessage::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_id() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.id)
  return _impl_.id_.Release();
}
inline void ChatMessage::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.id)
}

// string content = 2;
inline void ChatMessage::clear_content() {
  _impl_.content_.ClearToEmpty();
}
inline const std::string& ChatMessage::content() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.content)
  return _internal_content();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_content(ArgT0&& arg0, ArgT... args) {
 
 _impl_.content_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.content)
}
inline std::string* ChatMessage::mutable_content() {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.content)
  return _s;
}
inline const std::string& ChatMessage::_internal_content() const {
  return _impl_.content_.Get();
}
inline void ChatMessage::_internal_set_content(const std::string& value) {
  
  _impl_.content_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_content() {
  
  return _impl_.content_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_content() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.content)
  return _impl_.content_.Release();
}
inline void ChatMessage::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    
  } else {
    
  }
  _impl_.content_.SetAllocated(content, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.content)
}

// string sender_id = 3;
inline void ChatMessage::clear_sender_id() {
  _impl_.sender_id_.ClearToEmpty();
}
inline const std::string& ChatMessage::sender_id() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.sender_id)
  return _internal_sender_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_sender_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.sender_id)
}
inline std::string* ChatMessage::mutable_sender_id() {
  std::string* _s = _internal_mutable_sender_id();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.sender_id)
  return _s;
}
inline const std::string& ChatMessage::_internal_sender_id() const {
  return _impl_.sender_id_.Get();
}
inline void ChatMessage::_internal_set_sender_id(const std::string& value) {
  
  _impl_.sender_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_sender_id() {
  
  return _impl_.sender_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_sender_id() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.sender_id)
  return _impl_.sender_id_.Release();
}
inline void ChatMessage::set_allocated_sender_id(std::string* sender_id) {
  if (sender_id != nullptr) {
    
  } else {
    
  }
  _impl_.sender_id_.SetAllocated(sender_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_id_.IsDefault()) {
    _impl_.sender_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.sender_id)
}

// string sender_name = 4;
inline void ChatMessage::clear_sender_name() {
  _impl_.sender_name_.ClearToEmpty();
}
inline const std::string& ChatMessage::sender_name() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.sender_name)
  return _internal_sender_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_sender_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sender_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.sender_name)
}
inline std::string* ChatMessage::mutable_sender_name() {
  std::string* _s = _internal_mutable_sender_name();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.sender_name)
  return _s;
}
inline const std::string& ChatMessage::_internal_sender_name() const {
  return _impl_.sender_name_.Get();
}
inline void ChatMessage::_internal_set_sender_name(const std::string& value) {
  
  _impl_.sender_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_sender_name() {
  
  return _impl_.sender_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_sender_name() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.sender_name)
  return _impl_.sender_name_.Release();
}
inline void ChatMessage::set_allocated_sender_name(std::string* sender_name) {
  if (sender_name != nullptr) {
    
  } else {
    
  }
  _impl_.sender_name_.SetAllocated(sender_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sender_name_.IsDefault()) {
    _impl_.sender_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.sender_name)
}

// string receiver_id = 5;
inline void ChatMessage::clear_receiver_id() {
  _impl_.receiver_id_.ClearToEmpty();
}
inline const std::string& ChatMessage::receiver_id() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.receiver_id)
  return _internal_receiver_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_receiver_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.receiver_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.receiver_id)
}
inline std::string* ChatMessage::mutable_receiver_id() {
  std::string* _s = _internal_mutable_receiver_id();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.receiver_id)
  return _s;
}
inline const std::string& ChatMessage::_internal_receiver_id() const {
  return _impl_.receiver_id_.Get();
}
inline void ChatMessage::_internal_set_receiver_id(const std::string& value) {
  
  _impl_.receiver_id_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_receiver_id() {
  
  return _impl_.receiver_id_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_receiver_id() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.receiver_id)
  return _impl_.receiver_id_.Release();
}
inline void ChatMessage::set_allocated_receiver_id(std::string* receiver_id) {
  if (receiver_id != nullptr) {
    
  } else {
    
  }
  _impl_.receiver_id_.SetAllocated(receiver_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.receiver_id_.IsDefault()) {
    _impl_.receiver_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.receiver_id)
}

// string timestamp = 6;
inline void ChatMessage::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& ChatMessage::timestamp() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.timestamp)
}
inline std::string* ChatMessage::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.timestamp)
  return _s;
}
inline const std::string& ChatMessage::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void ChatMessage::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_timestamp() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.timestamp)
  return _impl_.timestamp_.Release();
}
inline void ChatMessage::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.timestamp)
}

// .chatmsg.ChatMessageType message_type = 7;
inline void ChatMessage::clear_message_type() {
  _impl_.message_type_ = 0;
}
inline ::chatmsg::ChatMessageType ChatMessage::_internal_message_type() const {
  return static_cast< ::chatmsg::ChatMessageType >(_impl_.message_type_);
}
inline ::chatmsg::ChatMessageType ChatMessage::message_type() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.message_type)
  return _internal_message_type();
}
inline void ChatMessage::_internal_set_message_type(::chatmsg::ChatMessageType value) {
  
  _impl_.message_type_ = value;
}
inline void ChatMessage::set_message_type(::chatmsg::ChatMessageType value) {
  _internal_set_message_type(value);
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.message_type)
}

// string message_cmd = 8;
inline void ChatMessage::clear_message_cmd() {
  _impl_.message_cmd_.ClearToEmpty();
}
inline const std::string& ChatMessage::message_cmd() const {
  // @@protoc_insertion_point(field_get:chatmsg.ChatMessage.message_cmd)
  return _internal_message_cmd();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ChatMessage::set_message_cmd(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_cmd_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:chatmsg.ChatMessage.message_cmd)
}
inline std::string* ChatMessage::mutable_message_cmd() {
  std::string* _s = _internal_mutable_message_cmd();
  // @@protoc_insertion_point(field_mutable:chatmsg.ChatMessage.message_cmd)
  return _s;
}
inline const std::string& ChatMessage::_internal_message_cmd() const {
  return _impl_.message_cmd_.Get();
}
inline void ChatMessage::_internal_set_message_cmd(const std::string& value) {
  
  _impl_.message_cmd_.Set(value, GetArenaForAllocation());
}
inline std::string* ChatMessage::_internal_mutable_message_cmd() {
  
  return _impl_.message_cmd_.Mutable(GetArenaForAllocation());
}
inline std::string* ChatMessage::release_message_cmd() {
  // @@protoc_insertion_point(field_release:chatmsg.ChatMessage.message_cmd)
  return _impl_.message_cmd_.Release();
}
inline void ChatMessage::set_allocated_message_cmd(std::string* message_cmd) {
  if (message_cmd != nullptr) {
    
  } else {
    
  }
  _impl_.message_cmd_.SetAllocated(message_cmd, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_cmd_.IsDefault()) {
    _impl_.message_cmd_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:chatmsg.ChatMessage.message_cmd)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace chatmsg

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::chatmsg::ChatMessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chatmsg::ChatMessageType>() {
  return ::chatmsg::ChatMessageType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chat_5ftypes_5fsamples_2eproto
