#pragma once

#include <stdexcept>

namespace tbs {

/** @addtogroup TBS
 * @{
 */

/// @brief Application error data structre.
struct AppError
{
   AppError();
   AppError(const std::string msg, const std::string& src = "", const char* fl = "", int ln = 0);

   std::string fullMessage;
   std::string message;
   std::string source;
   std::string file;
   int line;
};


/// @brief Exception class used in Tobasa, derived from std::runtime_error.
class AppException
   : public std::runtime_error
{
public:

   AppException(const AppError& appErr);
   AppException(const std::string& msg, const std::string& src ="", const char* fl = "", int ln = 0);
   AppException(const char* msg, const std::string& src = "", const char* fl = "", int ln = 0);
   AppException(const std::exception &ex, const std::string& src = "", const char* fl = "", int ln = 0);

   AppError appError;
};


/// @brief Exception generated by std::variant
class VariantException
   : public tbs::AppException
{
public:

   VariantException(const std::string& msg, const std::string& src = "")
      : tbs::AppException(msg.c_str(), src)
   {}
};


/// @brief Exception generated by enum conversions
class TypeException
   : public tbs::AppException
{
public:

   TypeException(const std::string& msg, const std::string& src = "")
      : tbs::AppException(msg.c_str(), src)
   {}
};


/// @brief Exception generated by cryptography operations
class CryptException
   : public std::runtime_error
{
public:

   CryptException(const std::string& msg)
      : std::runtime_error(msg.c_str())
   {}
};


/** @}*/

} // namespace tbs
