#pragma once

#include <memory>
#include <string>
#include <functional>

namespace tbs {
namespace http {

/** \addtogroup HTTP
 * @{
 */

enum class HttpVersion
{
   one,
   two,
   three
};

/// Http server connnection id
using ConnectionId = uint64_t;


constexpr int32_t ERROR_CODE_NONE        = -1000;
constexpr int32_t ERROR_CODE_EXCEPTION   = -1001;
constexpr int32_t ERROR_CODE_DATA_FAIL   = -1002;
constexpr int32_t ERROR_CODE_PARSER_FAIL = -1011;
constexpr int32_t ERROR_CODE_WRITE_FAIL  = -1012;
constexpr int32_t ERROR_CODE_READ_FAIL   = -1013;


enum class ErrorType
{
   internal,     // error generated by us
   system,       // error generated by system or asio lib(std::system_error)
   exception,    // error by exception
   none
};

struct ErrorData
{
   std::string  message  {};
   ErrorType    type     {ErrorType::none};
   int32_t      code     {ERROR_CODE_NONE};
   ConnectionId connId   {0};
   std::string  source   {};
};

enum class TimerType
{
   read,
   write,
   process
};

struct TimeOutData
{
   ConnectionId connId         {false};
   TimerType    timerType;
   std::string  message;
   int32_t      timeoutSeconds {0};
};

enum class InstanceType
{
   http_server,
   http_client
};

struct ConnectionInfo
{
   ConnectionId connId     {0};
   std::string  remoteEndpoint;
   bool         closed     {false};
   bool         tls        {false};
   bool         websocket  {false};
   std::string  identifier;
   std::string  startTime;
   std::string  duration;
};

class Connection;
class WebSocket;
class WebSocketContext;

using ConnectionPtr = std::shared_ptr<Connection>;
using WebSocketPtr = std::shared_ptr<WebSocket>;
using WebSocketContextPtr = std::shared_ptr<WebSocketContext>;


/// @brief OnComplete Handler
/// Callback function invoked when a connection wants to close/complete successfully.
/// @param ConnectionId
/// @param std::string Message or reason for the connection closure.
using OnComplete = std::function<void(ConnectionId, const std::string&)>;

/// OnError Handler
/// Callback function invoked when a connection wants to close because an error occurs.
/// @param ErrorData
using OnError = std::function<void(const ErrorData&)>;

/// @brief OnTimeOut Handler
/// Callback function invoked when a connection wants to close because of times out.
/// @param TimeOutData
using OnTimeOut = std::function<void(const TimeOutData&)>;

/// @brief OnClosed handler
/// Callback function invoked when a connection closed successfuly
/// @param ConnectionId
using OnClosed = std::function<void(ConnectionId)>;

/// @brief Connect Failed handler
/// @param std::string
using OnConnectFailed = std::function<void(const std::string&)>;



/// @brief Connection Error Handler
/// Callback function invoked when an error occured.
/// At this point, the connection is already closed and the underlying socket is terminated.
/// @param ErrorData
using OnConnectionError = std::function<void(const ErrorData&)>;

/// @brief Connection Closed Handler
/// Callback function invoked when a connection is closed and the underlying socket is terminated.
/// @param ConnectionId
using OnConnectionClosed = std::function<void(ConnectionId)>;

/// @brief OnConnectionTimeOut Handler
/// Callback function invoked when a connection operation time out.
/// At this point, the connection is already closed and the underlying socket is terminated.
/// @param TimeOutData
using OnConnectionTimeOut = std::function<void(const TimeOutData&)>;

/// @brief WebSocket Send Error Handler
/// @param ErrorData
using WsSendErrorHandler = std::function<void(const ErrorData&)>;

/** @}*/

} // namespace http
} // namespace tbs