#ifdef TOBASA_HTTP_USE_HTTP2

#include <tobasa/util_string.h>
#include "tobasahttp/server/http2_lib.h"

namespace tbs {
namespace http2 {

namespace {
nghttp2_nv makeNvInternal(const std::string &name, const std::string &value,
                          bool no_index, uint8_t nv_flags) 
{
   uint8_t flags;
   flags = nv_flags | (no_index ? NGHTTP2_NV_FLAG_NO_INDEX : NGHTTP2_NV_FLAG_NONE);

   return {
      (uint8_t *)name.c_str(), 
      (uint8_t *)value.c_str(), 
      name.size(),
      value.size(), 
      flags
   };
}
} // namespace

namespace {
nghttp2_nv makeNvInternal(const StringRef &name, const StringRef &value,
                          bool no_index, uint8_t nv_flags) 
{
   uint8_t flags;
   flags = nv_flags | (no_index ? NGHTTP2_NV_FLAG_NO_INDEX : NGHTTP2_NV_FLAG_NONE);

   return {
      (uint8_t *)name.c_str(), 
      (uint8_t *)value.c_str(), 
      name.size(),
      value.size(), 
      flags
   };
}
}

nghttp2_nv makeNv(const std::string &name, const std::string &value, bool no_index) 
{
   return makeNvInternal(name, value, no_index, NGHTTP2_NV_FLAG_NONE);
}

nghttp2_nv makeNv(const StringRef &name, const StringRef &value, bool no_index) 
{
   return makeNvInternal(name, value, no_index, NGHTTP2_NV_FLAG_NONE);
}


// This function was generated by genheaderfunc.py.  Inspired by h2o
// header lookup.  https://github.com/h2o/h2o
int lookupToken(const StringRef &name) 
{
   switch (name.size()) 
   {
      case 2:
         switch (name[1]) 
         {
            case 'e':
               if (util::streq("t"_sr, name, 1)) {
                  return HD_TE;
               }
            break;
         }
         break;
      case 3:
         switch (name[2]) 
         {
            case 'a':
               if (util::streq("vi"_sr, name, 2)) {
                  return HD_VIA;
               }
               break;
         }
         break;
      case 4:
         switch (name[3]) 
         {
            case 'e':
               if (util::streq("dat"_sr, name, 3)) {
                  return HD_DATE;
               }
               break;
            case 'k':
               if (util::streq("lin"_sr, name, 3)) {
                  return HD_LINK;
               }
               break;
            case 't':
               if (util::streq("hos"_sr, name, 3)) {
                  return HD_HOST;
               }
               break;
         }
         break;
      case 5:
         switch (name[4]) 
         {
            case 'h':
               if (util::streq(":pat"_sr, name, 4)) {
                  return HD__PATH;
               }
               break;
            case 't':
               if (util::streq(":hos"_sr, name, 4)) {
                  return HD__HOST;
               }
               break;
         }
         break;
      case 6:
         switch (name[5]) 
         {
            case 'e':
               if (util::streq("cooki"_sr, name, 5)) {
                  return HD_COOKIE;
               }
               break;
            case 'r':
               if (util::streq("serve"_sr, name, 5)) {
                  return HD_SERVER;
               }
               break;
            case 't':
               if (util::streq("expec"_sr, name, 5)) {
                  return HD_EXPECT;
               }
               break;
         }
         break;
      case 7:
         switch (name[6]) 
         {
            case 'c':
               if (util::streq("alt-sv"_sr, name, 6)) {
                  return HD_ALT_SVC;
               }
               break;
            case 'd':
               if (util::streq(":metho"_sr, name, 6)) {
                  return HD__METHOD;
               }
               break;
            case 'e':
               if (util::streq(":schem"_sr, name, 6)) {
                  return HD__SCHEME;
               }
               if (util::streq("upgrad"_sr, name, 6)) {
                  return HD_UPGRADE;
               }
               break;
            case 'r':
               if (util::streq("traile"_sr, name, 6)) {
                  return HD_TRAILER;
               }
               break;
            case 's':
               if (util::streq(":statu"_sr, name, 6)) {
                  return HD__STATUS;
               }
               break;
         }
         break;
      case 8:
         switch (name[7]) 
         {
            case 'n':
               if (util::streq("locatio"_sr, name, 7)) {
                  return HD_LOCATION;
               }
               break;
            case 'y':
               if (util::streq("priorit"_sr, name, 7)) {
                  return HD_PRIORITY;
               }
               break;
            }
         break;
      case 9:
         switch (name[8]) 
         {
            case 'd':
               if (util::streq("forwarde"_sr, name, 8)) {
                  return HD_FORWARDED;
               }
               break;
            case 'l':
               if (util::streq(":protoco"_sr, name, 8)) {
                  return HD__PROTOCOL;
               }
               break;
         }
         break;
      case 10:
         switch (name[9]) 
         {
            case 'a':
               if (util::streq("early-dat"_sr, name, 9)) {
                  return HD_EARLY_DATA;
               }
               break;
            case 'e':
               if (util::streq("keep-aliv"_sr, name, 9)) {
                  return HD_KEEP_ALIVE;
               }
               break;
            case 'n':
               if (util::streq("connectio"_sr, name, 9)) {
                  return HD_CONNECTION;
               }
               break;
            case 't':
               if (util::streq("user-agen"_sr, name, 9)) {
                  return HD_USER_AGENT;
               }
               break;
            case 'y':
               if (util::streq(":authorit"_sr, name, 9)) {
                  return HD__AUTHORITY;
               }
               break;
         }
         break;
      case 12:
         switch (name[11]) 
         {
            case 'e':
            if (util::streq("content-typ"_sr, name, 11)) {
               return HD_CONTENT_TYPE;
            }
            break;
         }
         break;
      case 13:
         switch (name[12]) 
         {
            case 'l':
               if (util::streq("cache-contro"_sr, name, 12)) {
                  return HD_CACHE_CONTROL;
               }
               break;
         }
         break;
      case 14:
         switch (name[13]) 
         {
            case 'h':
               if (util::streq("content-lengt"_sr, name, 13)) {
                  return HD_CONTENT_LENGTH;
               }
               break;
            case 's':
               if (util::streq("http2-setting"_sr, name, 13)) {
                  return HD_HTTP2_SETTINGS;
               }
               break;
         }
         break;
      case 15:
         switch (name[14]) 
         {
            case 'e':
               if (util::streq("accept-languag"_sr, name, 14)) {
                  return HD_ACCEPT_LANGUAGE;
               }
               break;
            case 'g':
               if (util::streq("accept-encodin"_sr, name, 14)) {
                  return HD_ACCEPT_ENCODING;
               }
               break;
            case 'r':
               if (util::streq("x-forwarded-fo"_sr, name, 14)) {
                  return HD_X_FORWARDED_FOR;
               }
               break;
         }
         break;
      case 16:
         switch (name[15]) 
         {
            case 'n':
               if (util::streq("proxy-connectio"_sr, name, 15)) {
                  return HD_PROXY_CONNECTION;
               }
               break;
         }
         break;
      case 17:
         switch (name[16]) 
         {
            case 'e':
               if (util::streq("if-modified-sinc"_sr, name, 16)) {
                  return HD_IF_MODIFIED_SINCE;
               }
               break;
            case 'g':
               if (util::streq("transfer-encodin"_sr, name, 16)) {
                  return HD_TRANSFER_ENCODING;
               }
               break;
            case 'o':
               if (util::streq("x-forwarded-prot"_sr, name, 16)) {
                  return HD_X_FORWARDED_PROTO;
               }
               break;
            case 'y':
               if (util::streq("sec-websocket-ke"_sr, name, 16)) {
                  return HD_SEC_WEBSOCKET_KEY;
               }
               break;
         }
         break;
      case 20:
         switch (name[19]) 
         {
            case 't':
               if (util::streq("sec-websocket-accep"_sr, name, 19)) {
                  return HD_SEC_WEBSOCKET_ACCEPT;
               }
               break;
         }
         break;
   }
   return -1;
}

}
}

#endif //TOBASA_HTTP_USE_HTTP2